name = "Prominence II [RPG]"
author = "ElocinDev"
version = "v2.8.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8f4dadb72fe122971c6dd2e33a652043949cb6e28ff173a0b8b9301acff149b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
