name = "Prominence II [RPG]"
author = "ElocinDev"
version = "v2.8.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aef904cc461dfb9d7fb845ffc64ec9e1f046e00fe2cd7c831e129f2818a663b3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
